### ISSUE TITLE
coffee support doesn't build

### ISSUE THREAD

**Issue by shaunc** [paulRbr/generator-webapp-rjs#3]
with "app.coffee" rather than "app.js" HEAD gives the following requirejs error:

Running "autoprefixer:dist" (autoprefixer) task
File ".tmp/styles/main.css" created.

Running "requirejs:dist" (requirejs) task

Tracing dependencies for: main
Error: ENOENT, no such file or directory '/Volumes/Macintosh HD/Users/shauncutts/src/y/app/scripts/app.js'
In module tree:
    main

{ [Error: Error: ENOENT, no such file or directory '/Volumes/Macintosh HD/Users/shauncutts/src/y/app/scripts/app.js'
In module tree:
    main

```
at Object.fs.openSync (fs.js:338:18)
```

]
  originalError: 
   { [Error: ENOENT, no such file or directory '/Volumes/Macintosh HD/Users/shauncutts/src/y/app/scripts/app.js']
     errno: 34,
     code: 'ENOENT',
     path: '/Volumes/Macintosh HD/Users/shauncutts/src/y/app/scripts/app.js',
     syscall: 'open',
     fileName: '/Volumes/Macintosh HD/Users/shauncutts/src/y/app/scripts/app.js',

**Comment by paulRbr** [comment]
Thanks for pointing it out.

That's now fixed in 0.4.8
